### ISSUE TITLE
see if movie already exists in library

### ISSUE THREAD

**Issue by mycoopdev** [RuudBurger/CouchPotatoExtension#3]
Hi Ruud, thanks for your fantastic work. I am developer and would like to create a new extension (or add functionality to your extension).

When on IMDB.com webpage they extension will turn yellow if the movie already exists in my Plex/XBMC/etc library. That way, users do not have to keep checking their local library to see if the movie already exists before snatching it with CouchPotato. 

To start with IMDB can you tell me what API's I should look at to complete this feature?

**Comment by RuudBurger** [comment]
I forgot I enabled issues for this repo. So 1 year later. If you still interested please let me know at info (at) couchpota.to
