### ISSUE TITLE
CouchPotatoExtension can't find movies on pages.

### ISSUE THREAD

**Issue by rafeek** [RuudBurger/CouchPotatoExtension#5]
Using Firefox 32.0 and v1.0.2 of the extension, I went to blu-ray.com, IMDB, HMV.com and Amazon.com and the extension presented an alert box with the following when I clicked on the icon:

"Doesn't seem to be a page CouchPotato can find a movie on."

**Comment by RuudBurger** [comment]
You need to be on a (single) movie page supported websites.
