### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by Zapitron** [RuudBurger/CouchPotatoExtension#7]
How does the browser plugin determine whether or not it's looking at a movie page?

Is there anything I can put on a page (without the plugin having to know any special rules for that site) to tell the plugin that it's a movie page, and which movie it's about?  I'm thinking in terms of any movie review pages which might like to be more couchpotato-friendly.

**Comment by RuudBurger** [comment]
You need to add a plugin to https://github.com/RuudBurger/CouchPotatoServer/tree/master/couchpotato/core/media/movie/providers/userscript 
Check out the existing one on how they work.
