### ISSUE TITLE
div is half way covering the "Add" button 

### ISSUE THREAD

**Issue by razorloves** [RuudBurger/CouchPotatoExtension#8]
Windows 8.1 using latest chrome stable and latest cp extension v1.1.2.
When attempting to press the "Add" button for a movie on IMDB, the top half of the button is covered by another div, so only the bottom half of the button is clickable.
This problem has existed since your 5 Jan update.
A quick workaround to fix issue is to revert a change you made to /src/common/style.js line 143.
Change absolute to relative.

Here's a screenshot showing the problem
https://www.dropbox.com/s/iktywwbw2inmpvt/Screenshot%202015-01-19%2019.04.04.png?dl=0

Thanks

**Comment by RuudBurger** [comment]
Thanks, fixed in 1.1.3
